### PR TITLE
fix image types

### PR DESCRIPTION
**Pull request by MaxBittker**
this is what the api return me :)

### CODE REVIEW

**Comment by pdelfan** [comment]
Hi @MaxBittker, thanks for letting me know. :) I'll come back in a few days to review, update the tests, and push the changes. I'll see if I can set up routine tests to automatically catch any bugs or outdated responses in future

**Comment by MaxBittker** [comment]
thanks @pdelfan, no rush, appreciate the library. 

I noticed other minor differences as well, for instance total_pages on channel doesn't seem to exist (?)

**Comment by pdelfan** [comment]
You're welcome! If I recall, there are some missing attributes that should exist according to the API documentation, as well as extra attributes which aren't documented. At the time I decided to follow the current (V2) documentation instead of the actual behaviour, going for consistency and hoping that in future they'd be updated.

It probably makes more sense to omit them entirely because those who use this package are not looking at the official docs anyway. I'll likely make some changes to reflect the current behaviour of the API.

**Comment by pdelfan** [comment]
Block image type is now updated ([see 0555c8b](https://github.com/pdelfan/arena-typed/commit/0555c8b258e6b87742e739cbb325864ca9f0e634))

**Pull request closed without merging**
